---

- name: set_rcfiles
  copy: src={{ item }} dest=/home/{{ username }}/.{{ item }}
  with_flattened:
    - rc_files

- name: create_i3_folder
  file: path=/home/{{ username }}/.i3 state=directory

- name: set_i3config
  copy: src=i3config dest=/home/{{ username }}/.i3/config

- name: create_i3blocks
  file: path=/home/{{ username }}/.config/i3/blocks state=directory

- name: set_i3_scripts
  copy: src=i3blocks dest=/home/{{ username }}/.config/i3/ mode="a+x"

- name: set_i3blocks
  copy: src=i3blocks.conf dest=/home/{{ username }}/.i3blocks.conf

- name: create_user_config_directory
  file: path=/home/{{ username }}/.config/systemd/user state=directory

- name: set_user_config
  template: src={{ item }}.service dest=/home/{{ username }}/.config/systemd/user/{{ item }}.service
  with_flattened:
    - user_configs

- name: enable_user_config
  command: systemctl --user enable {{ item }}.service
  with_flattened:
    - user_configs

- name: start_user_config
  command: systemctl --user start {{ item }}.service
  with_flattened:
    - user_configs

