---

- name: install_pacman_packages
  pacman: name={{ item }} state=present
  with_flattened:
    - pacman_packages

- name: install_yaourt_packages
  command: yaourt -S {{ item }} --noconfirm
  with_flattened:
    - yaourt_packages

- name: set_rcfiles
  copy: src={{ item }} dest=/home/{{ username }}/.{{ item }}
  with_flattened:
    - rc_files

- name: create_i3_folder
  file: path=/home/{{ username }}/.i3 state=directory

- name: set_i3config
  copy: src=i3config dest=/home/{{ username }}/.i3/config