#!/bin/sh

xmodmap ~/.Xmodmap
xbindkeys
/usr/bin/start-pulseaudio-x11 &
dispad &
dropbox &
sudo sh /etc/profile.d/keyboard-permissions.sh
xrdb -merge -I$HOME ~/.Xresources &
wine ~/.wine/drive_c/Program\ Files\ \(x86\)/1Password\ 4/Agile1pAgent.exe &
exec i3
