#!/bin/sh

xmodmap ~/.Xmodmap
xbindkeys
/usr/bin/start-pulseaudio-x11 &
dispad &
dropbox &
sudo sh /etc/profile.d/keyboard-permissions.sh
exec i3
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
xrandr --dpi 184
wine ~/.wine/drive_c/Program\ Files\ \(x86\)/1Password\ 4/Agile1pAgent.exe &
