#!/bin/sh

xmodmap ~/.Xmodmap
xbindkeys
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
/usr/bin/start-pulseaudio-x11 &
dispad &
dropbox &
sudo sh /etc/profile.d/keyboard-permissions.sh
exec i3
