---
# file: site.yml

- hosts: all
  gather_facts: no
  roles:
    - {role: base, tags: ['bootstrap', 'all'], sudo: yes}
    - {role: personal, tags: ['personal', 'all'], sudo: yes, sudo_user: "{{ username }}"}
    - {role: desktop, tags: ['desktop', 'all'], remote_user: "{{ username }}"}
    - {role: languages, tags: ['languages', 'all'], remote_user: "{{ username }}"}
