---

- name: check_if_yaourt_packages_are_already_installed
  command: pacman -Q {{item}}
  register: packages_presence
  with_items: yaourt_packages
  ignore_errors: yes
  changed_when: "packages_presence|failed"

- name: install_package_if_necessary
  command: yaourt -S {{item.item}} --noconfirm
  when: item|failed
  with_items: packages_presence.results

- name: symlink_ack
  file: src=/usr/bin/vendor_perl/ack dest=/usr/bin/ack state=link
  sudo: yes

- name: create_pinentry_folder
  file: path=/usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/ state=directory
  sudo: yes

- name: symlink_pinentry
  file: src=/usr/bin/pinentry-gtk-2 dest=/usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac state=link
  sudo: yes

- name: enable_pulseaudio
  command: systemctl --user enable pulseaudio.socket

- name: set_rcfiles
  copy: src={{ item }} dest=/home/{{ username }}/.{{ item }}
  with_flattened:
    - rc_files

- name: create_i3_folder
  file: path=/home/{{ username }}/.i3 state=directory

- name: set_i3config
  copy: src=i3config dest=/home/{{ username }}/.i3/config

- name: create_i3blocks
  file: path=/home/{{ username }}/.config/i3/blocks state=directory

- name: set_i3_scripts
  copy: src=i3blocks dest=/home/{{ username }}/.config/i3/ mode="a+x"

- name: set_i3blocks
  copy: src=i3blocks.conf dest=/home/{{ username }}/.i3blocks.conf

- name: create_user_config_directory
  file: path=/home/{{ username }}/.config/systemd/user state=directory

- name: fix_keyboard_permissions
  copy: src=keyboard-permissions.sh dest=/etc/profile.d/keyboard-permissions.sh mode="a+x"
  sudo_user: root
  sudo: yes

- name: fix_hw_lights
  copy: src={{ item }} dest=/usr/bin/{{ item }} mode="a+x"
  sudo_user: root
  sudo: yes
  with_flattened:
    - hw_light_files

- name: set_user_config
  template: src={{ item }}.service dest=/home/{{ username }}/.config/systemd/user/{{ item }}.service
  with_flattened:
    - user_configs

- name: enable_user_config
  command: systemctl --user enable {{ item }}.service
  with_flattened:
    - user_configs

- name: start_user_config
  command: systemctl --user start {{ item }}.service
  with_flattened:
    - user_configs
