---

- name: check_if_yaourt_packages_are_already_installed
  command: pacman -Q {{item}}
  register: packages_presence
  with_items: yaourt_packages
  ignore_errors: yes
  changed_when: "packages_presence|failed"

- name: install_package_if_necessary
  command: yaourt -S {{item.item}} --noconfirm
  when: item|failed
  with_items: packages_presence.results

- name: create_postgres_db
  shell: "su - postgres -c \"initdb --locale en_US.UTF-8 -D '/var/lib/postgres/data'\""
  sudo: yes
  args:
    creates: /var/lib/postgres/data

- name: enable_services
  service: name={{ item }} enabled=yes state=started
  sudo: yes
  with_flattened:
    - enable_services


- name: clone_rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=/home/{{ username }}/.rbenv

- name: clone_ruby_build
  git: repo=git://github.com/sstephenson/ruby-build.git dest=/home/{{ username }}/.rbenv/plugins/ruby-build
