---

- name: update_cache
  pacman: update_cache=yes

- name: install_pacman_packages
  pacman: name={{ item }} state=present
  with_flattened:
    - pacman_packages

- name: create_group_admins
  group: name=admins state=present

- name: create_user_{{ username }}
  user: name={{ username }} shell=/usr/bin/fish groups=admins

- name: add_admins_to_sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%admins' line='%admins ALL=(ALL) NOPASSWD: ALL'"

- name: install_yaourt_packages
  command: su - {{ username }} -c "yaourt -S {{ item }} --noconfirm"
  with_flattened:
    - yaourt_packages

- name: check_if_bootstrapped
  shell: cat /etc/mkinitcpio.conf | grep nouveau
  register: bootstrapped
  ignore_errors: yes

- include: bootstrap.yml
  when: "bootstrapped.rc != 0"